export const supportedLanguages = ["en", "zh", "fr"] as const;
export type Language = (typeof supportedLanguages)[number];

const en = {
  "nav.today": "Today", "nav.learn": "Learn", "nav.review": "Review", "nav.library": "Library", "nav.progress": "Progress", "nav.settings": "Settings", "nav.subtitle": "Study Instrument",
  "settings.title": "Settings", "settings.intro": "Choose the language used for navigation, controls, and system explanations.", "settings.language": "System language", "settings.english": "English", "settings.chinese": "Chinese", "settings.french": "French", "settings.saved": "Language preference saved.", "settings.saving": "Saving…", "settings.note": "French vocabulary, examples, and quoted source material remain in their original language.",
  "library.title": "Library", "library.search": "Search vocabulary…", "library.all": "All", "library.due": "Due", "library.difficult": "Difficult", "library.new": "New", "library.favorites": "Favorites", "library.collection": "Collection", "library.allCollections": "All collections", "library.word": "Word", "library.meaning": "Meaning", "library.status": "Status", "library.reviewDate": "Review", "library.learned": "Learned", "library.pending": "Meaning pending", "library.empty": "No words match these filters.", "library.loadMore": "Load more", "library.loading": "Loading…", "library.filters": "Filters", "library.favorite": "Favorite", "library.databaseError": "Database unavailable", "library.queryError": "Library query failed", "library.sortAscending": "Sort ascending", "library.sortDescending": "Sort descending",
  "learn.vocabulary": "Vocabulary", "learn.word": "Word", "learn.of": "of", "learn.loading": "Loading vocabulary…", "learn.databaseError": "Database unavailable", "learn.notReady": "Learning data is not ready.", "learn.back": "Back to library", "learn.meaningPending": "Meaning pending", "learn.playWord": "Play word", "learn.playSentence": "Play sentence", "learn.source": "Source", "learn.forms": "Conjugation and forms", "learn.addFavorite": "Add to favorites", "learn.favorited": "Saved as favorite", "learn.next": "Next",
  "review.databaseError": "Database unavailable", "review.cannotStart": "Review cannot start.", "review.back": "Back", "review.complete": "Session complete", "review.wellDone": "Well done.", "review.noneDue": "No more study-ready words are due.", "review.backToday": "Back to Today", "review.preparing": "Preparing your session…", "review.listen": "Listen", "review.choose": "Choose the correct definition", "review.listenExample": "Listen to example", "review.continue": "Continue", "review.check": "Check",
  "today.greeting": "Hello, Jasmine Wang.", "today.ready": "Your daily study session is ready.", "today.calibrated": "The instrument is calibrated.", "today.start": "Start review", "today.checkData": "Check data", "today.program": "Today’s programme", "today.learn": "words to learn", "today.review": "words to review", "today.difficult": "difficult words", "today.recent": "Recent progress", "today.streak": "Current streak", "today.activeCollection": "Active collection", "today.connect": "Connect PostgreSQL and import the listening collection", "today.today": "Today",
  "progress.title": "Progress", "progress.intro": "Your journey towards NCLC 7 mastery.", "progress.target": "Target summary", "progress.level": "Current estimated level", "progress.active": "Active vocabulary", "progress.studied": "Words studied", "progress.current": "Current", "progress.targetLevel": "Target", "progress.consistency": "Consistency (last 30 days)", "progress.days": "study days logged in the current window.", "progress.retention": "Retention quality", "progress.reviews": "Reviews", "progress.lapses": "Lapses", "progress.priority": "Priority review", "progress.missed": "Missed {count} times", "progress.ready": "Ready for recall",
  "pos.noun": "noun", "pos.verb": "verb", "pos.adj": "adjective", "pos.adv": "adverb",
  "debug.eyebrow": "System status", "debug.title": "PostgreSQL vocabulary catalog", "debug.intro": "The normalized SQL catalog is the only runtime vocabulary source. Private JSON remains an import artifact.", "debug.database": "Database URL", "debug.ready": "Ready", "debug.missing": "Missing", "debug.schema": "Schema", "debug.auth": "Authentication mode", "debug.dev": "Development", "debug.setup": "Copy .env.example to .env.local, start PostgreSQL, run the migrations, and import the listening dataset.", "debug.open": "Open library",
} as const;

export type MessageKey = keyof typeof en;
const zh: Record<MessageKey, string> = {
  "nav.today": "今日", "nav.learn": "学习", "nav.review": "复习", "nav.library": "词库", "nav.progress": "进度", "nav.settings": "设置", "nav.subtitle": "学习工具",
  "settings.title": "设置", "settings.intro": "选择导航、按钮和系统说明所使用的语言。", "settings.language": "系统语言", "settings.english": "英语", "settings.chinese": "中文", "settings.french": "法语", "settings.saved": "语言偏好已保存。", "settings.saving": "正在保存…", "settings.note": "法语词汇、例句和引用的原始材料会保留原文。",
  "library.title": "词库", "library.search": "搜索词汇…", "library.all": "全部", "library.due": "待复习", "library.difficult": "困难", "library.new": "新词", "library.favorites": "收藏", "library.collection": "词集", "library.allCollections": "全部词集", "library.word": "单词", "library.meaning": "释义", "library.status": "状态", "library.reviewDate": "复习时间", "library.learned": "已学习", "library.pending": "释义待完善", "library.empty": "没有符合筛选条件的单词。", "library.loadMore": "加载更多", "library.loading": "加载中…", "library.filters": "筛选", "library.favorite": "收藏", "library.databaseError": "数据库不可用", "library.queryError": "词库查询失败", "library.sortAscending": "升序排列", "library.sortDescending": "降序排列",
  "learn.vocabulary": "词汇", "learn.word": "第", "learn.of": "个，共", "learn.loading": "正在加载词汇…", "learn.databaseError": "数据库不可用", "learn.notReady": "学习数据尚未准备好。", "learn.back": "返回词库", "learn.meaningPending": "释义待完善", "learn.playWord": "播放单词", "learn.playSentence": "播放例句", "learn.source": "来源", "learn.forms": "变位与词形", "learn.addFavorite": "加入收藏", "learn.favorited": "已收藏", "learn.next": "下一个",
  "review.databaseError": "数据库不可用", "review.cannotStart": "无法开始复习。", "review.back": "返回", "review.complete": "本次复习完成", "review.wellDone": "做得好。", "review.noneDue": "目前没有到期且可学习的单词。", "review.backToday": "返回今日", "review.preparing": "正在准备复习…", "review.listen": "播放", "review.choose": "请选择正确释义", "review.listenExample": "播放例句", "review.continue": "继续", "review.check": "检查",
  "today.greeting": "你好，Jasmine Wang。", "today.ready": "今天的学习内容已经准备好。", "today.calibrated": "学习工具已校准。", "today.start": "开始复习", "today.checkData": "检查数据", "today.program": "今日计划", "today.learn": "个待学习单词", "today.review": "个待复习单词", "today.difficult": "个困难单词", "today.recent": "近期进度", "today.streak": "连续学习", "today.activeCollection": "当前词集", "today.connect": "请连接 PostgreSQL 并导入听力词集", "today.today": "今天",
  "progress.title": "学习进度", "progress.intro": "迈向 NCLC 7 的学习历程。", "progress.target": "目标概览", "progress.level": "当前估算等级", "progress.active": "活跃词汇", "progress.studied": "已学习单词", "progress.current": "当前", "progress.targetLevel": "目标", "progress.consistency": "最近 30 天学习情况", "progress.days": "个学习日记录在当前周期内。", "progress.retention": "记忆质量", "progress.reviews": "复习次数", "progress.lapses": "遗忘次数", "progress.priority": "优先复习", "progress.missed": "答错 {count} 次", "progress.ready": "可以开始回忆",
  "pos.noun": "名词", "pos.verb": "动词", "pos.adj": "形容词", "pos.adv": "副词",
  "debug.eyebrow": "系统状态", "debug.title": "PostgreSQL 词汇目录", "debug.intro": "规范化的 SQL 目录是唯一的运行时词汇来源；私有 JSON 仅作为导入文件保留。", "debug.database": "数据库地址", "debug.ready": "已就绪", "debug.missing": "缺失", "debug.schema": "数据库结构", "debug.auth": "认证模式", "debug.dev": "开发模式", "debug.setup": "请将 .env.example 复制为 .env.local，启动 PostgreSQL，运行迁移并导入听力数据。", "debug.open": "打开词库",
};
const fr: Record<MessageKey, string> = {
  "nav.today": "Aujourd’hui", "nav.learn": "Apprendre", "nav.review": "Réviser", "nav.library": "Bibliothèque", "nav.progress": "Progression", "nav.settings": "Réglages", "nav.subtitle": "Instrument d’étude",
  "settings.title": "Réglages", "settings.intro": "Choisissez la langue de la navigation, des commandes et des explications du système.", "settings.language": "Langue du système", "settings.english": "Anglais", "settings.chinese": "Chinois", "settings.french": "Français", "settings.saved": "Préférence linguistique enregistrée.", "settings.saving": "Enregistrement…", "settings.note": "Le vocabulaire français, les exemples et les sources citées restent dans leur langue d’origine.",
  "library.title": "Bibliothèque", "library.search": "Rechercher un mot…", "library.all": "Tous", "library.due": "À réviser", "library.difficult": "Difficiles", "library.new": "Nouveaux", "library.favorites": "Favoris", "library.collection": "Collection", "library.allCollections": "Toutes les collections", "library.word": "Mot", "library.meaning": "Sens", "library.status": "Statut", "library.reviewDate": "Révision", "library.learned": "Appris", "library.pending": "Sens en attente", "library.empty": "Aucun mot ne correspond à ces filtres.", "library.loadMore": "Charger plus", "library.loading": "Chargement…", "library.filters": "Filtres", "library.favorite": "Favori", "library.databaseError": "Base de données indisponible", "library.queryError": "Échec de la recherche", "library.sortAscending": "Trier par ordre croissant", "library.sortDescending": "Trier par ordre décroissant",
  "learn.vocabulary": "Vocabulaire", "learn.word": "Mot", "learn.of": "sur", "learn.loading": "Chargement du vocabulaire…", "learn.databaseError": "Base de données indisponible", "learn.notReady": "Les données d’apprentissage ne sont pas prêtes.", "learn.back": "Retour à la bibliothèque", "learn.meaningPending": "Sens en attente", "learn.playWord": "Écouter le mot", "learn.playSentence": "Écouter la phrase", "learn.source": "Source", "learn.forms": "Conjugaison et formes", "learn.addFavorite": "Ajouter aux favoris", "learn.favorited": "Ajouté aux favoris", "learn.next": "Suivant",
  "review.databaseError": "Base de données indisponible", "review.cannotStart": "La révision ne peut pas commencer.", "review.back": "Retour", "review.complete": "Session terminée", "review.wellDone": "Bien joué.", "review.noneDue": "Aucun autre mot prêt à étudier n’est à réviser.", "review.backToday": "Retour à aujourd’hui", "review.preparing": "Préparation de la session…", "review.listen": "Écouter", "review.choose": "Choisissez la définition correcte", "review.listenExample": "Écouter l’exemple", "review.continue": "Continuer", "review.check": "Vérifier",
  "today.greeting": "Bonjour, Jasmine Wang.", "today.ready": "Votre session d’étude quotidienne est prête.", "today.calibrated": "L’instrument est calibré.", "today.start": "Commencer la révision", "today.checkData": "Vérifier les données", "today.program": "Programme du jour", "today.learn": "mots à apprendre", "today.review": "mots à réviser", "today.difficult": "mots difficiles", "today.recent": "Progression récente", "today.streak": "Série en cours", "today.activeCollection": "Collection active", "today.connect": "Connectez PostgreSQL et importez la collection d’écoute", "today.today": "Auj.",
  "progress.title": "Progression", "progress.intro": "Votre parcours vers la maîtrise du NCLC 7.", "progress.target": "Résumé de l’objectif", "progress.level": "Niveau actuel estimé", "progress.active": "Vocabulaire actif", "progress.studied": "Mots étudiés", "progress.current": "Actuel", "progress.targetLevel": "Objectif", "progress.consistency": "Régularité (30 derniers jours)", "progress.days": "jours d’étude enregistrés dans la période actuelle.", "progress.retention": "Qualité de rétention", "progress.reviews": "Révisions", "progress.lapses": "Oublis", "progress.priority": "Révision prioritaire", "progress.missed": "Manqué {count} fois", "progress.ready": "Prêt pour le rappel",
  "pos.noun": "nom", "pos.verb": "verbe", "pos.adj": "adjectif", "pos.adv": "adverbe",
  "debug.eyebrow": "État du système", "debug.title": "Catalogue lexical PostgreSQL", "debug.intro": "Le catalogue SQL normalisé est l’unique source lexicale d’exécution. Le JSON privé reste un artefact d’importation.", "debug.database": "Adresse de la base", "debug.ready": "Prête", "debug.missing": "Manquante", "debug.schema": "Schéma", "debug.auth": "Mode d’authentification", "debug.dev": "Développement", "debug.setup": "Copiez .env.example vers .env.local, démarrez PostgreSQL, exécutez les migrations et importez les données d’écoute.", "debug.open": "Ouvrir la bibliothèque",
};

export const messages: Record<Language, Record<MessageKey, string>> = { en, zh, fr };
export function isLanguage(value: unknown): value is Language { return supportedLanguages.includes(value as Language); }
export function translate(language: Language, key: MessageKey, values?: Record<string, string | number>): string {
  let value = messages[language][key];
  for (const [name, replacement] of Object.entries(values ?? {})) value = value.replace(`{${name}}`, String(replacement));
  return value;
}
export function translatePartOfSpeech(language: Language, value: string): string {
  const key = `pos.${value}` as MessageKey;
  return key in messages[language] ? messages[language][key] : value;
}
